# pulled from ubuntu
FROM node:12.20.2-alpine as base

RUN apk add tzdata

ENV TZ America/Sao_Paulo

MAINTAINER Leonardo Nobre <leonardo.nobre@agu.gov.br>

ENV NODE_OPTIONS=--max-old-space-size=8192

RUN npm config set unsafe-perm true

RUN mv /usr/local/bin/node /usr/local/bin/node_bin

COPY docker/dev/node.sh /usr/local/bin/node

RUN chmod +x /usr/local/bin/node

RUN npm install npm@6.14.11 -g

FROM base as dev

WORKDIR /app

EXPOSE 4200

ENTRYPOINT ["sh", "/app/docker/dev/docker-entrypoint.sh"]
