# pulled from ubuntu
FROM node:12.16.2-alpine

RUN apk add tzdata

ENV TZ America/Sao_Paulo

MAINTAINER Leonardo Nobre <leonardo.nobre@agu.gov.br>

ENV NODE_OPTIONS=--max-old-space-size=8192

WORKDIR /app

COPY package.json /app/package.json

RUN npm config set unsafe-perm true

RUN npm install npm@latest -g

RUN npm install -g @angular/cli@9.1.7

RUN npm install

RUN npm rebuild node-sass

EXPOSE 4200

ENTRYPOINT ["sh", "/app/docker/dev/docker-entrypoint.sh"]
