version: '3'
services:
    angular:
        build:
            context: .
            dockerfile: ./DockerFile_SUPP
        ports:
            - 80:80
        volumes:
            - '.:/app'
        tty: true
        command: tail -f /dev/null
