version: '3'
services:
    angular:
        build:
            context: .
            dockerfile: ./DockerFile_SUPP
        ports:
            - 80:80
        volumes:
            - '.:/app'
        tty: true
        command: tail -f /dev/null
        networks:
            supp_frontend_network:
                ipv4_address: 192.168.70.10

networks:
    supp_frontend_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.70.0/24
