# pulled from ubuntu
FROM ubuntu:18.04

MAINTAINER Leonardo Nobre <leonardo.nobre@agu.gov.br>

# instalacao dos pacotes basicos
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y tzdata && apt-get install -y --allow-unauthenticated \
	wget vim curl git unzip jq apt-transport-https ca-certificates software-properties-common zlib1g-dev libxml2-dev

ENV NVM_VERSION v0.34.0
ENV NODE_VERSION v10.16.0
ENV NVM_DIR /usr/local/nvm
RUN mkdir $NVM_DIR
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/$NODE_VERSION/bin:$PATH

RUN echo "source $NVM_DIR/nvm.sh && \
    nvm install $NODE_VERSION && \
    nvm alias default $NODE_VERSION && \
    nvm use default" | bash
	

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#COPY . /app
WORKDIR /app

EXPOSE 80

ENTRYPOINT ["sh", "/app/docker-entrypoint-dev.sh"]
