version: '3'
services:
    angular-dev:
        container_name: angular-dev
        build:
            context: .
            dockerfile: ./docker/dev/DockerFile
        ports:
            - 4200:4200
        volumes:
            - '.:/app'
        tty: true
        command: tail -f /dev/null
        networks:
            supp_frontend_network:
                ipv4_address: 192.168.70.10

    angular-prod:
        container_name: angular-prod
        build:
            context: .
            dockerfile: ./docker/prod/DockerFile
        ports:
            - 4200:4200
        volumes:
            - '.:/app'
        tty: true
        command: tail -f /dev/null
        networks:
            supp_frontend_network:
                ipv4_address: 192.168.70.11

networks:
    supp_frontend_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.70.0/24
