# pulled from ubuntu
FROM ubuntu:18.04

MAINTAINER Leonardo Nobre <leonardo.nobre@agu.gov.br>

# instalacao dos pacotes basicos
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y tzdata && apt-get install -y --allow-unauthenticated \
	wget vim curl git unzip jq apt-transport-https ca-certificates software-properties-common zlib1g-dev libxml2-dev

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --allow-unauthenticated nodejs npm
	

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#COPY . /app
WORKDIR /app

EXPOSE 80

ENTRYPOINT ["/app/docker-entrypoint-dev.sh"]
