# build
FROM node:12.16.2-alpine

ENV NODE_OPTIONS=--max-old-space-size=8192

WORKDIR /app

COPY package.json /app/package.json

RUN npm config set unsafe-perm true

RUN npm install npm@latest -g

RUN npm install -g @angular/cli@9.1.1

RUN npm install

RUN npm rebuild node-sass

COPY . /app

RUN node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --configuration staging

FROM nginx:alpine

COPY --from=build /app/docker/prod/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 4200

ENTRYPOINT ["sh", "/app/docker/hom/docker-entrypoint.sh"]
