# build
FROM node:12.19.0-alpine AS build

ENV NODE_OPTIONS=--max-old-space-size=8192

WORKDIR /var/www/html

COPY package.json /var/www/html/package.json

RUN npm config set unsafe-perm true

RUN npm install npm@latest -g

RUN npm install -g @angular/cli@11.0.0-next.6

RUN npm install

COPY . /var/www/html

RUN node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --configuration production

FROM nginx:stable-alpine

COPY --from=build /var/www/html/docker/prod/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /var/www/html/dist /usr/share/nginx/html

EXPOSE 4200

CMD ["nginx", "-g", "daemon off;"]