# build
FROM node:12.16.1-alpine AS build

WORKDIR /app

ENV NODE_OPTIONS=--max-old-space-size=8192

COPY package.json /app/package.json

RUN npm install npm@latest -g

RUN npm install -g @angular/cli@9.0.5

RUN npm install

RUN npm rebuild node-sass

COPY . /app

RUN node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod

FROM nginx:alpine

COPY --from=build /app/docker/prod/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx"]
