# build
FROM node:10.16.0-alpine AS build

WORKDIR /app

RUN npm install npm@latest -g

RUN npm install -g @angular/cli@7.3.9

RUN npm install

RUN npm rebuild node-sass

RUN node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod

FROM nginx:alpine

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/out/ /usr/share/nginx/html

EXPOSE 80
